### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by remiburtin**
Small doc fixes.

### CODE REVIEW

**Comment by vitaut** [comment]
Thank you!

**Comment by mwinterb** [comment]
@vitaut Does this fix #3027? It's still obviously busted, but I don't know how often /latest gets updated.

**Comment by vitaut** [comment]
latest points to the latest *released* docs so they won't be updated until the next release (unless manually patched). The dev docs LGTM: https://fmt.dev/dev/syntax.html#range-format-specifications.

**Comment by mwinterb** [comment]
> latest points to the latest _released_ docs so they won't be updated until the next release (unless manually patched). The dev docs LGTM: https://fmt.dev/dev/syntax.html#range-format-specifications.

Thanks for the correction for dev vs. latest. I know I will forget again, but at least now I have less of an excuse.

**Comment by vitaut** [comment]
Applied the fix retroactively.

**Pull request merged**
