### PR TITLE
fmt :: internal::do_throw(x) 

### PR DESCRIPTION
**Pull request by DBJDBJ**
FMT_THROW simplified

I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

**Comment by DBJDBJ** [comment]
I give up ...  I am curious how will <format> look like ... this here is becoming a "jack of all trades" or in English: "the mess" ...

**Comment by vitaut** [comment]
It's very tricky to do portably so I gave up too in the past.

**Comment by vitaut** [comment]
But tanks for trying.

**Comment by DBJDBJ** [comment]
Vitaut, {fmt}; I was "in", and it is great. I just do not get the release policy. 

In particular, I am looking after the `<format>`  header.   I assume that will be pure C++20 stuff?

I really can not understand what is/was the problem with my obvious simplification of `do_throw()` and `FMT_THROW` ... I assume (as Herb would say) "a wall of macros" will solve that one...

**Comment by vitaut** [comment]
`<format>` could be C++20 but {fmt} must be portable to be useful.

**Comment by DBJDBJ** [comment]
Thank you for your patience. 

Do you expect/think <format> will be asked to have `char16_t`, `char32_t` overloads?

**Comment by vitaut** [comment]
Noone will ask for them =). If there's a proposal these overloads will be added.

**Comment by DBJDBJ** [comment]
Is [this](https://stackoverflow.com/a/58909239/10870835) crucial to implement char8_t C++20? (besides being crucial for  char 16 and 32, it seems)

**Comment by vitaut** [comment]
There will be no char8_t std::format in C++20.

**Comment by DBJDBJ** [comment]
one of the key questions: all the three top compilers latest versions, have ni problems passing `char8_t *` to the `printf()` and printing it out properly. with warnings. And WG14 has no decision on that in the same time. 

I assume there is some compiler vendors clique :) who made that work, without WG21 or WG14 reaching a C++20 decision on `printf` + `char8_t`?

**Pull request closed without merging**
