### PR TITLE
Add basic_format_string::get()

### PR DESCRIPTION
**Pull request by huangqinjin**

### CODE REVIEW

**Comment by huangqinjin** [comment]
To conform with standard.

https://en.cppreference.com/w/cpp/utility/format/basic_format_string

**Comment by vitaut** [comment]
Thanks!

**Comment by phprus** [comment]
@vitaut 
``std::basic_format_string`` does not contain ``operator basic_string_view<Char>()``.
Maybe remove it and replace it with ``get()`` calls?

**Comment by vitaut** [comment]
{fmt} provides a lot of functionality not available in `std::format`, this is just one of them. I don't think we need to remove anything.

**Pull request merged**
