### PR TITLE
Add ability to join elements of std::initializer_list

### PR DESCRIPTION
**Pull request by Rapotkinnik**
I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR. Mostly looks good but please move this to `fmt/ranges.h` and apply clang-format to your changes.

**Comment by Rapotkinnik** [comment]
Sorry, but is it ok...

$ ./bin/Debug/ranges-test.exe                                                                                           [==========] Running 0 tests from 0 test cases.
[==========] 0 tests from 0 test cases ran. (0 ms total)
[  PASSED  ] 0 tests.

...or I ran a wrong test?

**Comment by vitaut** [comment]
`ranges-test` require C++14: https://github.com/fmtlib/fmt/blob/85050aa2e61cfc3c29cd8b74c472df1dd8db588c/test/ranges-test.cc#L17. You could move the `JoinInitializerList` test outside of the ifdef block but that's not critical.

**Comment by Rapotkinnik** [comment]
> 201402L

I built library this way cmake . -DCMAKE_CXX_STANDARD=14 and nothing changed...what was I doing wrong?=)

**Comment by vitaut** [comment]
My bad, it's `>` not `>=` in `__cplusplus > 201402L`, so it requires C++17.

**Comment by Rapotkinnik** [comment]
But when I did `cmake . -DCMAKE_CXX_STANDARD=17`
I got `E:\Workspace\fmt\test\gtest\gtest.h(9692): error C2039: 'tr1': is not a member of 'std' [E:\Workspace\fmt\test\gmock.vc
xproj]`...

Is it a bug?

**Comment by vitaut** [comment]
Looks like a gtest bug.

**Pull request merged**
