### PR TITLE
hello

### PR DESCRIPTION
**Pull request by shahsemil**
I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.
yes

### CODE REVIEW

**Comment by lahma** [comment]
I'd suggest [labeling this as spam](https://hacktoberfest.digitalocean.com/details#spam).

**Comment by shahsemil** [comment]
hey please accept my pull request as i made it to your repository because
it was in top 10 and will help me to be part of hacktoberfest

**Comment by foonathan** [comment]
But this pull request has absolutely nothing to do with this project?!  This is a  C++ project, you've added some random Java files. Even if this were a Java project, they are just spam with no benefit.

The point of pull requests is to contribute to the project, i.e. add some feature or fix some bug. Not add some random files in an unrelated programming language.

**Comment by eliaskosunen** [comment]
On that note: https://hacktoberfest.digitalocean.com/details#quality-standards

> [H]ere are examples of the PRs that we consider to be low-quality contributions (which we discourage):
> ...
> - PRs that are regarded by a project maintainer as a hindrance vs. helping
> - Something that's clearly an attempt to simply +1 your PR count for October

**Pull request closed without merging**
