### PR TITLE
Fix `FMT_INSTALL` with `FMT_MODULE`

### PR DESCRIPTION
**Pull request by yujincheng08**
Error:
```console
  install TARGETS target fmt is exported but not all of its interface file
  sets are installed
```

### CODE REVIEW

**Review by vitaut — COMMENTED** [review]
Thanks for the PR. Mostly looks good but I wonder if the include directory is the right place to install sources.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by yujincheng08** [comment]
@vitaut basically there's no "standard" place to place the install sources. So it's free to place anywhere, as long as `cmake` can help export the correct `FILE_SET` to dependants

**Comment by vitaut** [comment]
Merged, thanks!

**Pull request merged**
