### PR TITLE
Visual Studio: Fix C4702: unreachable code in pedantic mode

### PR DESCRIPTION
**Pull request by chronoxor**
I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

**Comment by chronoxor** [comment]
fmt\include\fmt\core.h(563): warning C4702: unreachable code
fmt\include\fmt\format.h(1144): warning C4702: unreachable code
fmt\include\fmt\format.h(1646): warning C4702: unreachable code
fmt\include\fmt\format.h(2014): warning C4702: unreachable code
fmt\include\fmt\format.h(2037): warning C4702: unreachable code
fmt\include\fmt\format.h(2057): warning C4702: unreachable code
fmt\include\fmt\format.h(2059): warning C4702: unreachable code

**Comment by vitaut** [comment]
Thanks for the PR. Is it possible to fix/workaround the warnings instead of suppressing them?

**Comment by chronoxor** [comment]
We cannot just remove the code after handler.on_error() because the implementation can be different. But VS 2019 warns for the default implementation which does FMT_THROW.

**Comment by chronoxor** [comment]
I suggest suppressing the Visual Studio warning for this case. I think this warning is false positive in this case.

**Comment by vitaut** [comment]
Does this only occur on VS2019? I was trying to repro on VC2017 on godbolt, but couldn't: https://godbolt.org/z/qO1zZa

**Comment by chronoxor** [comment]
Yes this issue appears only in new VS2019

**Comment by vitaut** [comment]
Hmm, I wasn't able to repro on 2019 either: https://godbolt.org/z/TulfIT (at least not with /W4). What compiler options do you use?

**Comment by chronoxor** [comment]
I use Level4 (/W4) & /WX to treat warnings as errors:

image
image

**Comment by chronoxor** [comment]
Just tried to rebuild without suppressing of the warnings and get the following output:

image

**Comment by vitaut** [comment]
OK, I managed to repro: https://godbolt.org/z/B2egiG

**Comment by vitaut** [comment]
Closing in favor of a simpler workaround: https://github.com/fmtlib/fmt/commit/ccd70f59eeed94770ab75817a3a08915148767b4

**Comment by chronoxor** [comment]
Thanks a lot!

**Pull request closed without merging**
