### PR TITLE
Rename MASTER_PROJECT to use FMT_ prefix

### PR DESCRIPTION
**Pull request by ClausKlein**
This prevent name conflicts with other projects

I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR but I don't think there is a conflict because `MASTER_PROJECT` is local to the fmt directory scope: https://cmake.org/cmake/help/latest/command/set.html#set-normal-variable

**Comment by vitaut** [comment]
Closing per comment above.

**Comment by ClausKlein** [comment]
Yes, if you see you project isolated.

We use i.e. fmt as a subproject and what happens if we use MASTER_PROJECT too?

**Comment by vitaut** [comment]
it shouldn't affect your `MASTER_PROJECT` because CMake variables are local to the directory by default (unless `PARENT_SCOPE` is specified).

**Pull request closed without merging**
