### PR TITLE
Simplifying format_decimal()

### PR DESCRIPTION
**Pull request by Roman-Koshelev**

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR but this would be a regression because `memcpy(..., 2)` generates better code in gcc than copying individual chars.

**Comment by foonathan** [comment]
Couldn't we then put the `if (is_constant_evaluated())` inside `copy2`?

**Comment by vitaut** [comment]
> Couldn't we then put the if (is_constant_evaluated()) inside copy2?

We could, PRs are welcome! =)

**Comment by Roman-Koshelev** [comment]
@vitaut What you said is only valid for gcc 7 and older. I will fix the PR

**Comment by vitaut** [comment]
It's true for gcc 10 as well, notice two move instructions in https://godbolt.org/z/qb4x39s33:

```asm
        movzx   ecx, BYTE PTR .LC0[rdx+1]
        movzx   edx, BYTE PTR .LC0[rdx]
```

**Comment by Roman-Koshelev** [comment]
https://godbolt.org/z/YKvoshP8K strange. Everything is optimized without inlining

**Comment by vitaut** [comment]
Strange indeed.

**Comment by Roman-Koshelev** [comment]
I fixed the PR

**Comment by Roman-Koshelev** [comment]
(Apparently it is necessary to rediscover for changes to come)

**Comment by vitaut** [comment]
Please submit a new PR.

**Pull request closed without merging**
