### PR TITLE
Rename check to fmt_check (fixes #2965) so that it works with UE

### LINKED ISSUE #2965: Visual studio 2019 compile error
Reporting, was using older fmt 5.x version fine.  Started working on a new project with latest master (fa2eb2d2e3ec5c21629f8ccd88ae05ec40b963fa), it has compile error (after removing module: in fmt.cc)

I'm able to put the old fmt 5.x in new project and compiles fine.

image

### PR DESCRIPTION
**Pull request by vampy**
Fixes https://github.com/fmtlib/fmt/issues/2965

### CODE REVIEW

**Comment by vampy** [comment]
Happy to rename it to something else if this name is not appropriate 🙏

**Comment by vitaut** [comment]
Thanks for the PR but `check` are properly namespaced/local names so there is no reason to rename them. If this is causing problems with some third-party macros please report to the project that defines them.

**Comment by vampy** [comment]
This is for unreal engine https://www.unrealengine.com/en-US/
Chance of them to rename the [`check` macro](https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/ProgrammingWithCPP/Assertions/) to something else is zero.

This change will not break anything but will allow unreal engine users to use this library.
I know this is not ideal, but this is the pain of using macros.

**Comment by vitaut** [comment]
Please report to UE. It is clearly a problematic API that should be fixed on their side by prefixing the macro.

**Pull request closed without merging**
