### PR TITLE
Release 3.0.1 (Dummy PR)

### PR DESCRIPTION
**Pull request by foonathan**
(This PR is just meant for discussing the bugfix release.)

Okay, I've `git cherry pick`ed every non-breaking bugfix I've noticed. Github's compare function is so smart and seems to compare this branch vs the 3.0.0 tag, so these are all the changes I've made.

I still need to update the changelog though.

### CODE REVIEW

**Comment by vitaut** [comment]
Cool, thanks for working on this! One minor comment: the version should probably be 3.1.0 because of the additions to the public API in `time.h` and elsewhere.

**Comment by foonathan** [comment]
What additions? I tried to only add pure bugfixes, no API additions.

**Comment by vitaut** [comment]
This one for instance: https://github.com/fmtlib/fmt/pull/399/commits/2a9f0a2608a50ab296d66a1d65d7cb850c90a90d

**Comment by foonathan** [comment]
Ah, you're right, I thought it was internal only.

Should I then make it 3.1.0 and also add stuff like the public format_system_error() function (or whatever the name was)?

**Comment by vitaut** [comment]
I'd go with a smaller, mostly bug fixing release right now and leave most of the new features to the later stage.

**Comment by foonathan** [comment]
Good, that was I was intending, I just need to remove that commit then.

**Comment by foonathan** [comment]
Alright, so I've done that and updated the ChangeLog. As soon as you give me green light (and concrete instructions on how to release it), the release goes live!

(BTW: I did some forced pushs in order to keep the branch clean, this messed up some CI builds and didn't seem to update the PR review properly, sorry for that :) ).

**Comment by vitaut** [comment]
Great job!

greenlightsgocleveland

In theory all you need to do is to run `support/manage.py release release-3.0.1`. You might need to change the date to `TBD` in `ChangeLog` to make it happy: https://github.com/fmtlib/fmt/blob/master/support/manage.py#L199. It should update the date automatically. Let me know if there are any issues with the script or feel free to modify it yourself if you like =).

**Comment by foonathan** [comment]
When I run the script I get a `No such file or directory: 'virtualenv'`` error.

**Comment by vitaut** [comment]
You need to have [`virtualenv`](https://virtualenv.pypa.io/en/stable/) installed to run the script.

**Comment by foonathan** [comment]
Okay, so I ran the script it failed finally with:

```
Counting objects: 3, done.
Delta compression using up to 6 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 326 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:fmtlib/fmt
 * [new branch]      release -> release
Traceback (most recent call last):
  File "support/manage.py", line 233, in <module>
    release(args)
  File "support/manage.py", line 227, in release
    raise Exception('Failed to create a release ' + str(r))
Exception: Failed to create a release <Response [404]>
```

Any idea?

**Comment by vitaut** [comment]
You need to get a GitHub API token from https://github.com/settings/tokens and pass it to the script in the environment variable `FMT_TOKEN`. I should have mentioned it earlier, but it's been a while since I used the script myself, sorry =).

**Comment by foonathan** [comment]
Alright, it is released.

**Comment by vitaut** [comment]
Awesome, thanks!

**Pull request closed without merging**
