### PR TITLE
Workaround for missing lconv support in android

### PR DESCRIPTION
**Pull request by dpantele**
Fixing https://github.com/fmtlib/fmt/issues/327

Better to check if this API really works on Android. 
Also please check if that is an OK use for the StringRef.

### CODE REVIEW

**Comment by dpantele** [comment]
@vitaut , do you have any idea why mingw fails and VS is fine? I don't have mingw environment at the moment

**Comment by dpantele** [comment]
What I could do blindly is to catch `std::runtime_error` and use std::locale("") in that case.

**Comment by vitaut** [comment]
Thanks for the PR. According to [this thread](https://sourceforge.net/p/mingw/mailman/message/31768770/):

> The GCC's libstdc++ does not support locales other than the C locale on MinGW. Somebody has to implement it first.

So I changed it back to C locale but added a detection for empty `lconv` in https://github.com/fmtlib/fmt/commit/3cefa72f2019616cc3610df9554743f74e4ade92. It would be even better to detect `lconv::thousands_sep` is there with SFINAE, but this simple solution should do for now. Does it work for you?

**Comment by Gachapen** [comment]
Hi, I have the same issue, but your fix (3cefa72) does not work. It's choosing the default `thousands_sep`:
```
In file included from fmt/posix.h:48:0,
                 from fmt/posix.cc:33:
fmt/format.h: In function 'fmt::StringRef fmt::internal::thousands_sep()':
fmt/format.h:915:60: error: 'struct lconv' has no member named 'thousands_sep'
 fmt::StringRef thousands_sep() { return std::localeconv()->thousands_sep; }
```

Anything I can do to help?

**Comment by vitaut** [comment]
@Gachapen Thanks for testing it. Could you check what is `sizeof(lconv)` on Android? I guess the size check is not very reliable, maybe I should use a proper SFINAE detection for `thousands_sep`.

**Comment by Gachapen** [comment]
@vitaut Just checked, it is 1.

**Comment by vitaut** [comment]
@Gachapen Thanks. Just realized that my "fix" is rubbish because the `thousands_sep` template is compiled anyway.

**Comment by Gachapen** [comment]
@vitaut Hehe, yes I see that now too :) 

This is a bit too complex for me (I'd just `#ifdef` it). I'll happily test any fix you can come up with.

**Comment by dpantele** [comment]
I will do the proper SFINAE version right now.

**Comment by dpantele** [comment]
SFINAE with c++98 looks really messy... What do you think about this approach? https://github.com/dpantele/fmt/commit/998bd2c40628128abbfa9807ce73d8f2a2308c5d

**Comment by vitaut** [comment]
@dpantele Definitely looks better but I wonder why the tests are failing on mingw.

**Comment by dpantele** [comment]
@vitaut I haven't pushed changes to the pull request branch, now all builds pass.

**Comment by Gachapen** [comment]
I can confirm that this now builds. Though is it safe to assume that the size should be less or equal to 1 when it has no members?

**Comment by vitaut** [comment]
@dpantele Got it. Could you squash the commits and rebase to current master?

@Gachapen You are right, the size check is not very robust. A better option is to detect `lconv::thousands_sep` specifically using something like http://stackoverflow.com/a/1007175/471164, but it will require more work.

**Comment by dpantele** [comment]
Ok, reabsed and cleaned-up in https://github.com/fmtlib/fmt/pull/328/commits/45a150945597b95102656c8f7a5819e08cf244ae

**Comment by vitaut** [comment]
Merged, thanks!

**Pull request merged**
