### PR TITLE
Use FMT_NOEXCEPT macro instead of noexcept

### PR DESCRIPTION
**Pull request by tohammer**
Replace all occurrences in non-test code.

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR but is there any problem with using `noexcept` directly?

**Comment by phprus** [comment]
@vitaut 
https://github.com/fmtlib/fmt/blob/a126b4d888dbdf254bc2b11fab8a5195951549f5/include/fmt/core.h#L148-L168
If I'm not mistaken, then ``FMT_NOEXCEPT`` is always ``noexcept``. ``FMT_NOEXCEPT`` was needed for older compilers that are not supported by the fmt now.

**Comment by vitaut** [comment]
We can definitely get rid of `FMT_DETECTED_NOEXCEPT` since all the supported compilers have `noexcept` but I wonder if the ability to disable `FMT_NOEXCEPT` is still used anywhere.

**Comment by phprus** [comment]
The code (core.h, lines 148-168) may be reduced to:
```c++
#ifndef FMT_NOEXCEPT 
# define FMT_NOEXCEPT noexcept
/* optional warning: */
#else
# warning FMT_NOEXCEPT is deprecated
#endif 
```
?

**Comment by vitaut** [comment]
Let's hear from @tohammer first.

**Pull request closed without merging**
