### PR TITLE
Fix build for the clang-10 / libstdc++-9 couple

### LINKED ISSUE #2490: fmt::v8: bigint build failure with clang-10
```C++
#define FMT_HEADER_ONLY
#include <fmt/format.h>
int main() 
{
  fmt::detail::bigint b;
  b.square();
}
```

causes

```
In file included from /opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:2983:
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format-inl.h:557:49: error: variable of non-literal type 'basic_memory_buffer<fmt::v8::detail::bigint::bigit, bigits_capacity>' (aka 'basic_memory_buffer<unsigned int, bigits_capacity>') cannot be defined in a constexpr function
    basic_memory_buffer<bigit, bigits_capacity> n(std::move(bigits_));
                                                ^
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:651:13: note: 'basic_memory_buffer<unsigned int, 32, std::allocator<unsigned int> >' is not literal because it has data member 'alloc_' of non-literal type 'std::allocator<unsigned int>'
  Allocator alloc_;
            ^
```

repro: https://godbolt.org/z/nT1TP4Wof ; maybe FMT_CONSTEXPR20 needs to start from clang-11 (where the above code compiles without issues)

### PR DESCRIPTION
**Pull request by jcelerier**
Fixes #2490

### CODE REVIEW

**Comment by vitaut** [comment]
Looks like this crashes clang for some reason: https://github.com/jcelerier/fmt/runs/3534703685

**Comment by jcelerier** [comment]
of course it works there....

from a ubuntu:18.04 image:
```
$ apt update
$ apt install git clang-9 gcc cmake build-essential
$ git clone https://github.com/jcelerier/fmt
$ mkdir build
$ cd build
$ CC=clang-9 CXX=clang++-9 cmake -DCMAKE_BUILD_TYPE=Debug  -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_STANDARD=11 -DFMT_DOC=OFF -DCMAKE_CXX_VISIBILITY_PRESET=hidden -DCMAKE_VISIBILITY_INLINES_HIDDEN=ON  -DFMT_PEDANTIC=ON -DFMT_WERROR=ON /fmt
$ make -j
```

do you see anything different I could be forgetting ?

**Comment by jcelerier** [comment]
also it seems to work here... https://github.com/fmtlib/fmt/runs/3534712060?check_suite_focus=true

I'm usually not the one to reach for the "bitflip-inducing cosmic ray" theory but...

**Comment by vitaut** [comment]
Could be a transient issue.

**Comment by vitaut** [comment]
Merged, thanks!

**Pull request merged**
