### PR TITLE
add oss fuzz badge

### PR DESCRIPTION
**Pull request by pauldreik**
Added a nice shiny oss fuzz badge. The link appears to be wrong, but it isn't, there have been no bugs found by oss fuzz so far :-)

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks!

**Comment by vitaut** [comment]
Hey @pauldreik, do you know why it says `coverage failing` but doesn't show any failures?

**Comment by pauldreik** [comment]
Where does it say that? Could you provide a link?

I know these places to look for information:
 - build logs at https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libfmt which work fine to watch, and fmt builds just fine.
 - the bug tracker, https://bugs.chromium.org/p/oss-fuzz/issues/list?colspec=ID%20Type%20Component%20Status%20Proj%20Reported%20Owner%20Summary&q=proj%3Dfmt&can=1 which is empty, could you please introduce some bug so we can verify that oss fuzz actually reports it :-)

And here is on the control panel at https://oss-fuzz.com/ which requires login with the account associated with the project. I find it cumbersome to use, it is not easy to browse around since one often get empty output even if "all" is selected.

**Comment by vitaut** [comment]
The badge itself was yellow for a while with the text in it saying "coverage failing". But it is back to green again so probably some transient issue. Thanks for the links.

**Pull request merged**
