### PR TITLE
Eliminate unreachable code warnings

### PR DESCRIPTION
**Pull request by gsjaardema**
The code following a `FMT_THROW` is unreachable since the exception does not return.  Some compilers (e.g. Nvidia) emit "Unreachable Code" warnings for this construct.  Since this is in an include file, the warning can be emitted many many times.

I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR. Looks like MSVC builds are failing.

**Comment by vitaut** [comment]
Could you post the full warning and compiler version? Instead of fixing the callsites the compiler should be added to the check here: https://github.com/fmtlib/fmt/blob/9e450911fa21af2271707ab3f554dcbf51ac1750/include/fmt/format.h#L89

**Comment by vitaut** [comment]
Unfortunately this won't work with exceptions disabled. Please see my earlier comment on the recommended solution instead.

**Comment by gsjaardema** [comment]
But if exceptions are disabled, don't you end up with the following:
```
  #define FMT_THROW(x)                                                                               \
    do {                                                                                             \
      static_cast<void>(sizeof(x));                                                                  \
      assert(false);                                                                                 \
    } while (false)
```
And in a release code if `NDEBUG` is defined, this will result in just skipping the error all together won't it?

Also, there are some unprotected throws in compile.h; should those be surrounded by a `FMT_THROW()`?

I will redo the PR

**Comment by vitaut** [comment]
Yes, that's why disabling exceptions is not recommended. Users can also override the default `FMT_THROW`.

**Comment by vitaut** [comment]
> Also, there are some unprotected throws in compile.h; should those be surrounded by a FMT_THROW()?

The whole compile.h is experimental, so I wouldn't bother with changing it yet.

**Pull request closed without merging**
