### PR TITLE
git is confusing

### PR DESCRIPTION
**Pull request by king7saksham**
I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

**Comment by eliaskosunen** [comment]
What?

**Comment by OttoWinter** [comment]
@eliaskosunen Please add the "invalid" tag to this PR.

This looks like a classic case of trying to get in PRs for the Hacktoberfest challenge (see also other PRs this account created: https://github.com/COPS-IITBHU/hello-cops/pull/330 https://github.com/COPS-IITBHU/Hacker-Introduction/pull/108 https://github.com/COPS-IITBHU/cops_namecards/pull/105)

Adding the "invalid" tag will stop it from counting toward the user's hacktoberfest PR count.

**Comment by vitaut** [comment]
I don't think closed PRs count.

**Comment by vitaut** [comment]
Although https://hacktoberfest.digitalocean.com/details#spam says that it should be both closed and labeled. Seems like they are just encouraging more spam.

**Comment by OttoWinter** [comment]
@vitaut Yep, they should be tagged invalid.

See also this answer in the [FAQ](https://hacktoberfest.digitalocean.com/faq)

> Do PRs have to be accepted/merged?
>
> No, they will still count unless they are spam, irrelevant, or labeled as invalid.

**Pull request closed without merging**
