### PR TITLE
Fixed some clang-tidy warnings

### PR DESCRIPTION
**Pull request by gabime**

### CODE REVIEW

**Comment by vitaut** [comment]
Looks good, but could you post the warnings and the repro command?

**Comment by gabime** [comment]
They come from `google-explicit-constructor` and `readability-isolate-declaration` checks  : 

```console
warning: single-argument constructors must be marked explicit to avoid unintentional implicit conversions [google-explicit-constructor]
    constexpr sprintf_specs(basic_format_specs<Char> specs)
              ^
              explicit 
```

and 

```console
warning: multiple declarations in a single statement reduces readability [readability-isolate-declaration]
                auto p = buf.data(), end = p + n;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by vitaut** [comment]
Merged with minor tweaks, thanks.

**Comment by gabime** [comment]
The pointer specifier was to avoid another clang tidy warning that gets triggered if removed ..

**Comment by vitaut** [comment]
What's the warning?

**Comment by gabime** [comment]
```readability-qualified-auto```

```console
warning: 'auto p' can be declared as 'auto *p' [readability-qualified-auto]
                auto p = buf.data();
                ^~~~~
                auto *
warning: 'auto end' can be declared as 'auto *end' [readability-qualified-auto]
                auto end = p + n;
                ^~~~~
                auto *

```

**Comment by vitaut** [comment]
Reapplied the auto change.

**Pull request closed without merging**
