### PR TITLE
Visual Studio 2017: warning C4456: declaration of 'result' hides prev…

### PR DESCRIPTION
**Pull request by chronoxor**
…ious local declaration

### CODE REVIEW

**Comment by vitaut** [comment]
Hi @chronoxor, thanks for the PR!

Could you please review https://github.com/fmtlib/fmt/blob/ebec00138bd10e949ff34955bcb096387cd32acc/CONTRIBUTING.md, particularly the part about licensing, and let me know if you agree with it being applied both to this PR and your earlier contributions?

**Comment by chronoxor** [comment]
Yes I agree. See no problems with the license.

**Comment by vitaut** [comment]
Great, thanks for confirmation. Also note that the future versions may be relicensed (probably as BSD + an optional clause to drop all requirements on binary redistribution): #1073

**Comment by chronoxor** [comment]
Does the PR require some other updates due to new licensing?

**Comment by vitaut** [comment]
> Does the PR require some other updates due to new licensing?

Not really. Merged and thanks again for the PR!

**Pull request merged**
