### PR TITLE
clang-tidy cleanups

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR but this is inconsistent with library conventions and breaks the build: https://travis-ci.org/github/fmtlib/fmt/jobs/684517793

**Comment by neheb** [comment]
Which commits?

**Comment by vitaut** [comment]
All of them for different reasons maybe except for making members const.

**Comment by vitaut** [comment]
Actually no, that's problematic too because those methods are semantically non-const.

**Comment by neheb** [comment]
The last three should be fine. The first two I understand.

**Comment by neheb** [comment]
The build breakage was caused by the third commit. I've fixed it locally.

**Pull request closed without merging**
