### PR TITLE
FMT_IF_CONSTEXPR

### PR DESCRIPTION
**Pull request by Neargye**
I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR but I'm not sure if it's necessary. The compiler will optimize the dead branches away. `if constexpr` is only needed when the code in the branch wouldn't compile otherwise.

**Comment by Neargye** [comment]
I decided to do it because I got such a compiler message
```
warning C4127: conditional expression is constant
note: consider using 'if constexpr' statement instead
```

**Comment by Neargye** [comment]
But overall you are right

**Comment by vitaut** [comment]
The warning can be suppressed with `const_check`, e.g. https://github.com/fmtlib/fmt/blob/a265e25b7924d7edec77c28ee76182e69bfcc3fe/include/fmt/format.h#L1612

**Comment by vitaut** [comment]
It's not great but a bit more readable than a macro.

**Pull request closed without merging**
