### PR TITLE
Fix build error on GCC-9

### PR DESCRIPTION
**Pull request by phprus**
Issue: #3092

### CODE REVIEW

**Comment by phprus** [comment]
@vitaut
I think it is necessary to add a GCC-9 compiler to CI for testing fmt on all current versions of GCC.

**Comment by vitaut** [comment]
LGTM but please rebase since there were some changes to `write_loc`.

**Comment by phprus** [comment]
@vitaut 
Rebased

**Comment by vitaut** [comment]
Thank you!

**Pull request merged**
