### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by HazardyKnusperkeks**
Fix some warnings.

### CODE REVIEW

**Review by vitaut — CHANGES_REQUESTED** [review]
Thank for the PR. In general looks good except for the `-Wsuggest-attribute=format` part which is a bit messy. Considering that this code is going away I suggest not trying to suppress it.

**Comment by phprus** [comment]
@vitaut 
Tell me please, sprintf is only used to print floating point numbers in hex format? Or not?

**Comment by vitaut** [comment]
> Tell me please, sprintf is only used to print floating point numbers in hex format?

Yes, `s(n)printf` is only used for hexfloat.

**Comment by HazardyKnusperkeks** [comment]
> Thank for the PR. In general looks good except for the `-Wsuggest-attribute=format` part which is a bit messy. Considering that this code is going away I suggest not trying to suppress it.

Is there an ETA on when it's going away?

**Review by vitaut — APPROVED** [review]

**Comment by vitaut** [comment]
Merged, thanks!

> Is there an ETA on when it's going away?

it will happen in the next (major) release some time next year. The actual code might be removed earlier in preparation for the release.

**Comment by HazardyKnusperkeks** [comment]
> it will happen in the next (major) release some time next year. The actual code might be removed earlier in preparation for the release.

We are hitting this warning in our tests (-Werror). When the code is going away, couldn't we just add the suppression, as it also will go away? I'd rather not change the our submodule to a fork.

**Comment by vitaut** [comment]
You can suppress the warnings with `FMT_SYSTEM` or other method. I don't think it makes sense to add a suppression that won't be included in any release.

**Pull request merged**
