### PR TITLE
Mt complex p2197 r0

### PR DESCRIPTION
**Pull request by tesch1**
This is not done, and probably not even good, but it's maybe a little better.

Probably need to re-think how to toggle iostreams compatibility, star or no star, and j or i.

Not sure if there's a way to get `sign` from the nested formatter?

### CODE REVIEW

**Comment by tesch1** [comment]
note to self: https://hackingcpp.com/cpp/libs/fmt.html#fp-numbers

**Comment by vitaut** [comment]
> Not sure if there's a way to get sign from the nested formatter?

No, you'll need to parse it in the `complex` formatter.

**Comment by vitaut** [comment]
@tesch1, do you plan to work on this in the nearest future? If not I will close the PR for now.

**Comment by tesch1** [comment]
perhaps not the nearest

**Comment by vitaut** [comment]
It goes without saying that you are always welcome to open a new PR or reopen this one.

**Pull request closed without merging**
