### PR TITLE
use memchr for finding '%' in formatting string in printf.h

### PR DESCRIPTION
**Pull request by rimathia**
I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR but could you elaborate what this is for?

**Comment by rimathia** [comment]
The goal here is to mirror the use of detail::find in format.h lines 2715 and 2730 with the goal of making printf with long format strings (order 1000 characters) faster. However, I don't have data to prove that this makes a difference, at this point the argument is purely by analogy: If it makes sense to use it in forma.h to search '{' and '}', it should make sense here as well.

**Comment by vitaut** [comment]
It doesn't really make sense here since the parsing logic is completely different. Also microoptimizations should be backed by data.

**Comment by rimathia** [comment]
Makes sense to me, thanks for getting to it so quickly.

**Pull request closed without merging**
