### PR TITLE
Improve std::complex formatter

### PR DESCRIPTION
**Pull request by phprus**
Based on ideas: #4034

Implemented:
- dynamic width
- dynamic precision
- ``sign``, ``nan`` and ``inf`` handling

### CODE REVIEW

**Comment by phprus** [comment]
@vitaut
please, review this PR.

**Review by vitaut — APPROVED** [review]
Thanks for the PR. All looks good but I'll merge it a bit later not to interfere with the upcoming patch release.

**Comment by phprus** [comment]
Current output ``(2+-2.2i)`` for ``complex<double>(2, -2.2)`` is a formatting error as I think.
Or is fix for this bug is not suitable to patch release?

**Comment by vitaut** [comment]
I missed the fix part. Makes sense to include in the patch release then.

**Pull request merged**
