### PR TITLE
buffer should declare virtual dtor

### PR DESCRIPTION
**Pull request by Finkman**
I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR but the destructor is non-virtual (and protected) intentionally.

**Comment by Finkman** [comment]
hm.. interessting.
It will result in:
`fmt/include/fmt/format.h:678:3: error: 'fmt::v7::basic_memory_buffer<wchar_t, 500, std::allocator<wchar_t> >' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]`

Compiled with clang [6,7,10] and gcc [7.5]
Is it an issue?

**Comment by vitaut** [comment]
It's a GCC bug 7302 but a PR to suppress the warning without making the dtor virtual is welcome.

**Comment by Finkman** [comment]
> It's a GCC bug 7302 but a PR to suppress the warning without making the dtor virtual is welcome.

I tried it with gcc 7.5, clang 9/10.
It seams that #1936 fixed it.

**Comment by vitaut** [comment]
Thanks for checking.

**Pull request closed without merging**
