### PR TITLE
Fixed issue #779

### PR DESCRIPTION
**Pull request by gabime**
This removes the shadow warnings produced by gcc.

### CODE REVIEW

**Comment by eliaskosunen** [comment]
@vitaut I told you ;) #771

**Comment by vitaut** [comment]
Merged in https://github.com/fmtlib/fmt/commit/c2fbadb9cf84dfee2667d9dd13ff71789eab8a4f with minor tweaks, thanks.

**Comment by vitaut** [comment]
@gabime, could you please review the updated [CONTIBUTING](https://github.com/fmtlib/fmt/blob/ebec00138bd10e949ff34955bcb096387cd32acc/CONTRIBUTING.md) document, particularly the part about licensing, and let me know if you agree with it being applied to your contributions to {fmt}? The library is likely to be relicensed (#1073) so I'm collecting approval from all earlier contributors. Thanks!

**Comment by gabime** [comment]
I agree. no problem.

**Pull request closed without merging**
