### PR TITLE
fix clang warnings

### PR DESCRIPTION
**Pull request by Lectem**
When building with c++14 and -Weverything, I encountered the following warnings which are now fixed : 
-  dynamic exception specifications are deprecated [-Wdeprecated]
- 'FMT_USE_OVERRIDE' is not defined, evaluates to 0 [-Wundef]
- definition of implicit copy constructor for 'FormatError' is deprecated because it has a user-declared destructor [-Wdeprecated]

### CODE REVIEW

**Comment by Lectem** [comment]
To make GCC compile while removing the deprecated warning of throw() for clang, I had to introduce a new define FMT_DESTRUCTOR_NOEXCEPT as the headers would still use throw() even when exceptions are disabled. It has the same behaviour as FMT_NOEXCEPT for compilers other than GCC.
It seems to be more of a libstdc++11 problem though, I'm not sure if it could pose problems for some versions of clang.

**Comment by foonathan** [comment]
I am personally not happy with the destructor noexcept workaround (but @vitaut opinion counts).
The problem could be solved more elegantly if we remove the destructor in the exception classes, because the implicitly generated one *should* be `throw()` in those cases automatically (IIRC). I'm guessing the destructors are there to avoid the weak vtable warning?

Anyways, I'd merge that PR (and would include it in the 3.0.1 I was just about to release), but I'm waiting on @vitaut opinion here.

**Comment by Lectem** [comment]
I wanted to remove the destructors at first too but I suspected they were added for a reason, it would be nice to confirm why.

**Comment by vitaut** [comment]
Merged with minor changes in https://github.com/fmtlib/fmt/commit/a5b9611e48f5a0e48c21c9c4c0aa88d3ddd8f61a. Thanks, @Lectem!

@foonathan, I'd prefer to remove dtors too, but as you correctly guessed they were added to prevent `-Wweak-vtables` warning in clang (https://github.com/fmtlib/fmt/commit/b26e76efe9417ea773bb1e6c6ce875646c71a346). Alternative suggestions are welcome.

**Comment by vitaut** [comment]
Hmm, the fix caused failures on Travis, so I moved it to the https://github.com/fmtlib/fmt/tree/warnings branch for further investigation.

**Comment by vitaut** [comment]
Merged to `master`: https://github.com/fmtlib/fmt/commit/8f455c10b0f1aee898f71313b21c43b098dadb34.

**Pull request closed without merging**
