### PR TITLE
std::filesystem::path is not format as a range

### PR DESCRIPTION
**Pull request by phprus**
Fix: #3322

### CODE REVIEW

**Comment by vitaut** [comment]
`std::filesystem::path` should be excluded by the recursive range check in https://github.com/fmtlib/fmt/blob/73b7cee7fb0d46487607f95a7fc67229a3aea17c/include/fmt/ranges.h#L509

See e.g. http://eel.is/c++draft/format#range.fmtkind-2. I wonder why it doesn't work on Windows?

**Comment by phprus** [comment]
@vitaut 

https://github.com/fmtlib/fmt/blob/73b7cee7fb0d46487607f95a7fc67229a3aea17c/include/fmt/ranges.h#L560-L564

On windows ``std::filesystem::path`` uses ``wchar_t``.
``is_range`` exclude ``std::filesystem::path`` on unix because ``std::filesystem::path`` is convertible to ``std::basic_string<char>``:
https://github.com/fmtlib/fmt/blob/73b7cee7fb0d46487607f95a7fc67229a3aea17c/include/fmt/ranges.h#L382-L387

On Windows ``std::filesystem::path`` does not convertible to ``std::basic_string<char>``.
Demo: https://godbolt.org/z/K1f1jPxjv

Original test for ``char`` (UNIX): https://github.com/fmtlib/fmt/blob/c644c753d7124b0161ad87003ce340ebfb0526c8/test/ranges-test.cc#L182-L191

**Comment by phprus** [comment]
@vitaut, what do you think about this PR?

**Comment by vitaut** [comment]
I think it's OK for `is_range` to return true for `path` on Windows and the root cause is broken recursion check (it didn't strip cvref). This should be fixed in https://github.com/fmtlib/fmt/commit/e0748e61ddc0cbef840596bf9748199a2197e613. So I'm closing this PR but thanks anyway, especially for the test case which has been added in the above commit.

**Pull request closed without merging**
